AWSTemplateFormatVersion: '2010-09-09'
Resources:
  sampleApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      Description: AWS Elastic Beanstalk Sample Application
  sampleApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName:
        Ref: sampleApplication
      Description: AWS ElasticBeanstalk Sample Application Version
      # taking war file from S3 bucket
      SourceBundle:
        S3Bucket: "london-bookapplication-02-12-2023"
        S3Key: londonBookProject.war
  sampleConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName:
        Ref: sampleApplication
      Description: AWS ElasticBeanstalk Sample Configuration Template
      OptionSettings:
      - Namespace: aws:ec2:vpc
        OptionName: VPCId
        # passing down the vpc id created by VPC2.yaml file
        Value: vpc-0b14057411ee06045
      - Namespace: aws:ec2:vpc
        OptionName: Subnets
        Value:
          Fn::Join:
          - ","
          # passing down the private subnet id created by VPC2.yaml file
          - - subnet-0b4b3e8c4206bcfb4
            - subnet-02f6901266f18ae57
      - Namespace: aws:ec2:vpc
        OptionName: ELBSubnets
        Value:
          Fn::Join:
          - ","
          # passing down the public subnet id created by VPC2.yaml file
          - - subnet-092e6b63dcdd52ba0
            - subnet-02c96d317b52cafd0
      - Namespace: aws:autoscaling:asg
        OptionName: MinSize
        Value: '2'
      - Namespace: aws:autoscaling:asg
        OptionName: MaxSize
        Value: '4'
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: EnvironmentType
        Value: LoadBalanced
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: IamInstanceProfile
        Value: aws-elasticbeanstalk-ec2-role
      - Namespace: aws:autoscaling:updatepolicy:rollingupdate
        OptionName: RollingUpdateEnabled
        Value: true

      - Namespace: aws:autoscaling:updatepolicy:rollingupdate
        OptionName: RollingUpdateType
        Value: Health

      - Namespace: aws:autoscaling:trigger
        OptionName: MeasureName
        Value: CPUUtilization

      - Namespace: aws:autoscaling:trigger
        OptionName: Unit
        Value: Percent

      - Namespace: aws:autoscaling:trigger
        OptionName: UpperThreshold
        Value: 70

      - Namespace: aws:autoscaling:trigger
        OptionName: LowerThreshold
        Value: 0
      SolutionStackName: 64bit Amazon Linux 2023 v5.1.1 running Tomcat 10 Corretto 17
  sampleEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName:
        Ref: sampleApplication
      Description: AWS ElasticBeanstalk Sample Environment
      TemplateName:
        Ref: sampleConfigurationTemplate
      VersionLabel:
        Ref: sampleApplicationVersion
